$(document).ready(function () {
    $("#registerForm").validate({
        rules:{
            firstName:{
                required:true,
                minlenght:1,
                maxlenght:15
            },
            lastName:{
                required:true,
                minlenght:1,
                maxlenght:15
            },
            username:{
                required:true,
                email:true,
                maxlenght:15
            },
            password:{
                required:true,
                minlenght:5,
                maxlenght:15
            }
        }
    })
});